server:
  port: 80


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-230-153-41.compute-1.amazonaws.com:5432/d2d9eg78vk9o74
    username: sdhduaanwkduvt
    password: 39aea87be673b7824634bfe2503a24ddc1a46b29d4b28d792e082578aa9b6a68
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    servlet:
      path: /api

  main:
    lazy-initialization: true

  jackson:
    date-format: yyyy-MM-dd



  mail:
    host: smtp.gmail.com
    port: 587
    password: befoyda1998
    username: farruxbekaxmadaliyev850@gmail.com


  servlet:
    multipart:
      max-file-size: 99MB
      max-request-size: 9999MB




#
#  spring.mail.host=email-smtp.us-west-2.amazonaws.com
#  spring.mail.username=username
#  spring.mail.password=password
#  spring.mail.properties.mail.transport.protocol=smtp
#  spring.mail.properties.mail.smtp.port=25
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true


